kairos/config/routes.rb
require 'api/root'

Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users, :path => "auth", :path_name => {
      :sign_in => 'login',
      :sign_out => 'logout'
  }

  resource :gitlab, controller: 'gitlab', only: [] do
    member do
      get :groups
      get '/projects/:id', to: :project
      get '/projects/', to: :projects
      get '/projects/:id/issues', to: :issues_for_project
      get :issues
    end
  end

  resource :profiles, only: [:show,] do
    member do
      put :reset_private_token
      put :update_gitlab_private_token
    end
  end

  resources :entries, only: [:create, :index, :destroy] do
    collection do
      get :import, to: :import_index
      post :import, to: :import_data
    end
  end

  mount API::Root => '/'

  root 'welcome#index'

end

kairos/app/helpers/layout_helper.rb
module LayoutHelper
  def page_title
    title_components = [configatron.app_name]

    saved_title = content_for(:title)
    title_components.unshift(saved_title) unless saved_title.blank?

    title_components.join(' • ')
  end

  def page_stylesheet_tag
    controller = params[:controller]

    @page_stylesheet_tags ||= {}
    @page_stylesheet_tags[controller] ||= begin
      css_path = Pathname.pwd.
          join('app/assets/stylesheets/pages').
          join("#{controller}.css.scss")
      css_path.exist? ? stylesheet_link_tag("pages/#{controller}") : ''
    end
  end

  def page_javascript_tag
    controller = params[:controller]

    @page_stylesheet_tags ||= {}
    @page_stylesheet_tags[controller] ||= begin
      css_path = Pathname.pwd.
          join('app/assets/javascripts/pages').
          join("#{controller}.js")
      css_path.exist? ? stylesheet_link_tag("pages/#{controller}") : ''
    end
  end
end

kairos/app/views/layouts/_flash.html.haml
.flash-container
  - if alert
    .flash-alert
      = alert

  - elsif notice
    .flash-notice
      = notice

kairos/app/views/layouts/_header.html.haml
%nav.main-nav.navbar.navbar-default.navbar-fixed-top
  .container
    -# Brand and toggle get grouped for better mobile display
    .navbar-header.page-scroll
      %button.navbar-toggle{ type: 'button', data: { toggle: 'collapse', target: '' }}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to configatron.app_name, root_path(:anchor => 'page-top'), :class => 'navbar-brand'
    -# Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        - if user_signed_in?
          %li
            = link_to entries_path do
              %i.fa.fa-pencil-square-o
                = t('action.entries')
      %ul.nav.navbar-nav.navbar-right
        %li.hidden
          = link_to configatron.app_name, root_path, :class => 'navbar-brand'
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{ id: 'user-settings',
              :data => { :target => '#', :toggle => 'dropdown' }}
              %img.user-avatar{ src: ''}
              %span.user-name
                = current_user.email
              %b.caret
            %ul.dropdown-menu{ role: 'menu', 'aria-labelledby'=>'user-settings'}
              %li
                = link_to profiles_path do
                  %i.fa.fa-user
                  = t('message.user.profile')
              %li
                %a
                  %i.fa.fa-gear
                  = t('message.user.settings')
              %li.divider
              %li
                = link_to import_entries_path do
                  %i.fa.fa-upload
                  = t('message.user.import')
              %li.divider
              %li
                = link_to destroy_user_session_path, :method => :delete do
                  %i.fa.fa-sign-out
                  = t('message.auth.sign_out')
        - else
          %li.page-scroll
            %a{ href: '#about' }
              About
          %li.page-scroll
            %a{ href: '#contact' }
              Contact
          %li
            = link_to t('message.auth.sign_in'), new_user_session_path, :class => "navbar-link"

kairos/app/views/layouts/application.html.haml
!!!
%html

  %head
    %title!= page_title
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1.0'}/
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    %link{rel:'icon', type:'image/png', href:'/favicon.png'}/
    %link{rel:'apple-touch-icon', type:'image/png', href:'/touch-icon.png'}/
    = stylesheet_link_tag :application, media: 'all'
    = page_stylesheet_tag
    = javascript_include_tag :application
    = page_javascript_tag
    = csrf_meta_tag
    = yield(:head)

  %body{ class: ["#{controller_name}-#{action_name}"] }
    = render 'layouts/header'
    = content_for?(:application_content) ? yield(:application_content) : yield