kairos/config/routes.rb
require 'api/root'

Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users, :path => "auth", :path_name => {
      :sign_in => 'login',
      :sign_out => 'logout'
  }

  resource :gitlab, controller: 'gitlab', only: [] do
    member do
      get :groups
      get '/projects/:id', to: :project
      get '/projects/', to: :projects
      get '/projects/:id/issues', to: :issues_for_project
      get :issues
    end
  end

  resource :profiles, only: [:show,] do
    member do
      put :reset_private_token
      put :update_gitlab_private_token
    end
  end

  resources :entries, only: [:create, :index, :destroy] do
    collection do
      get :import, to: :import_index
      post :import, to: :import_data
    end
  end

  mount API::Root => '/'

  root 'welcome#index'

end

kairos/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  before_filter :user

  def show
  end

  def reset_private_token
    if current_user.reset_authentication_token!
      flash[:notice] = t('profiles.message.token_successfully_updated')
    end

    redirect_to profiles_path
  end

  def update_gitlab_private_token
    if current_user.update_gitlab_authentication_token!(params[:token])
      flash[:notice] = t('profiles.message.token_successfully_updated')
    else
      flash[:alert] = t('profiles.message.token_failed_update')
    end

    redirect_to profiles_path
  end

  private

  def user
    @user = current_user
  end
end

kairos/app/views/profiles/show.html.haml
.container
  = render "layouts/flash"
  %h3
    = t('message.user.profile')
  %p
    = t('profiles.description')
  .profile
    %fieldset.update-kairos-token
      %legend
        = t('oauth.private_token')
      %div
        = form_for @user, url: reset_private_token_profiles_path, method: :put, html: { class: 'form', role: 'form'} do |f|
          .data
            %p
              = t('profiles.kairos.private_token.about')
              %span.cred
                = t('profiles.private_token.secret')
            %p.cgray
              - if current_user.private_token
                = text_field_tag :token, current_user.private_token, class: "form-control"
                %div
                  = f.submit t('profiles.action.reset'), data: { confirm: t('profiles.prompt.are_you_sure') }, class: "btn btn-primary btn-build-token"
              - else
                %span= t('profiles.kairos.private_token.not_configured_yet')
                = f.submit t('profiles.action.generate'), class: "btn success btn-build-token"
    %fieldset.update-gitlab-token
      %legend
        = 'Gitlab ' + t('oauth.private_token')
      %div
        = form_for @user, url: update_gitlab_private_token_profiles_path, method: :put, html: { class: 'form', role: 'form'} do |f|
          .data
            %p
              = t('profiles.gitlab.private_token.about')
            %p.cgray
              = text_field_tag :token, current_user.gitlab_token, class: "form-control"
              - if current_user.gitlab_token
                %div
                  = f.submit t('profiles.action.update'), data: { confirm: t('profiles.prompt.are_you_sure') }, class: "btn btn-primary btn-build-token"
              - else
                %div
                  %spant= t('profiles.gitlab.private_token.not_configured_yet')
                  = f.submit t('profiles.action.configure'), class: "btn success btn-build-token"