kairos/config/routes.rb
require 'api/root'

Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users, :path => "auth", :path_name => {
      :sign_in => 'login',
      :sign_out => 'logout'
  }

  resource :gitlab, controller: 'gitlab', only: [] do
    member do
      get :groups
      get '/projects/:id', to: :project
      get '/projects/', to: :projects
      get '/projects/:id/issues', to: :issues_for_project
      get :issues
    end
  end

  resource :profiles, only: [:show,] do
    member do
      put :reset_private_token
      put :update_gitlab_private_token
    end
  end

  resources :entries, only: [:create, :index, :destroy] do
    collection do
      get :import, to: :import_index
      post :import, to: :import_data
    end
  end

  mount API::Root => '/'

  root 'welcome#index'

end

kairos/app/models/entry.rb
require 'csv'

class Entry < ActiveRecord::Base
  extend ActiveSupport::Concern

  belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'
  belongs_to :activity, :class_name => 'Activity', :foreign_key => 'activity_id'

  validates_presence_of :date, :duration, :user, :activity, :group

  validates :duration, numericality: { greater_than: 0.0 }
  validates :group, numericality: { only_integer: true }
  validates :description, length: { maximum: 144 }
  validates :project, numericality: { only_integer: true }, allow_nil: true
  validates :issue, numericality: { only_integer: true }, allow_nil: true

  def date=(value)
    begin
      if /\d{1,2}\/\d{1,2}\/\d{4}/.match(value)
        write_attribute :date, Date.strptime(value, '%d/%m/%Y').strftime("%Y-%m-%d")
      else
        write_attribute :date, Date.strptime(value, '%Y-%m-%d').strftime("%Y-%m-%d")
      end
    rescue
      errors[:date] = 'date is invalid'
    end
  end

  # Import uploaded `file` data into `user` entries.
  def self.import(file, user)
    return if file.nil?

    processed = {
        skipped: 0,
        imported: 0
    }

    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      begin
        params = row.to_hash
        Entry.create! date: params[:date],
                      user: user,
                      duration: params[:duration].to_f,
                      activity: Activity.find_by(name: params[:activity].to_s),
                      group: params[:group].to_i,
                      project: params[:project].to_i,
                      issue: params[:issue].to_i,
                      description: params[:description].to_s
      rescue
        processed[:skipped] += 1
      else
        processed[:imported] += 1
      end
    end

    processed
  end
end

kairos/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  before_filter :user
  before_filter :gitlab_access_configured!

  def index
    @entry = Entry.new
    load_last_entries
  end

  def create
    @entry = Entry.new date: entry_params[:date],
                      user: current_user,
                      duration: entry_params[:duration].to_f,
                      activity_id: entry_params[:activity].to_i,
                      group: entry_params[:group].to_i,
                      description: entry_params[:description].to_s

    @entry.project = params[:entry][:project].to_i if params[:entry][:project]
    @entry.issue = params[:entry][:issue].to_i if params[:entry][:issue]

    if @entry.valid?
      @entry.save()
      redirect_to entries_path
    else
      flash[:alert] = @entry.errors.full_messages.join(' ')
      load_last_entries
      render :index
    end
  end

  def import_index
    render :import
  end

  def import_data
    processed = Entry.import(params[:file], current_user)

    puts processed

    if processed.nil?
      redirect_to entries_url, :alert => t('entries.alerts.bad_file')
    elsif processed[:skipped] > 0
      redirect_to entries_url, :alert => t('entries.alerts.many_errors_during_import', count: processed[:skipped])
    else
      redirect_to entries_url, :notice => t('notices.successfully_imported')
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_url, notice: t('notices.successfully_deleted')
  end

  private

  def load_last_entries
    @entries_for_today = @user.entries.where(:date => Date.today)
    @entries_for_yesterday = @user.entries.where(:date => Date.yesterday)
    @entries_for_week = @user.entries.where(:date => Date.today.beginning_of_week..Date.today)
    @entries = @user.entries.where('date < ?', Date.today.beginning_of_week)
  end

  def user
    @user = current_user
  end

  def entry_params
    params.require('entry').permit(:date, :duration, :activity, :group, :description, :project, :issue);
  end
end

kairos/app/views/entries/_entries_listing.html.haml
%section
  %header
    .time-container
      %span.title= title
      %span.hour= "#{entries.sum(:duration)} h"
  %table
    - entries.each do |entry|
      %tr
        %td.action
          .dropdown
            %button.btn.btn-default.btn-xs.dropdown-toggle{ id: "action-for-entry-#{entry.id}", 'data-toggle' => 'dropdown', :type => 'button' }
              %span.fa.fa-cog
            %ul.dropdown-menu.slidedown{ role: 'menu', 'aria-labelledby' => "action-for-entry-#{entry.id}" }
              %li{ role: 'presentation' }
                = link_to entry_path(entry), role: 'menuitem', method: :delete, data: { :confirm => t('prompt.are_you_sure') } do
                  %span.fa.fa-trash
                    Delete
        %td.details
          %span.activity= entry.activity.name
          %span.group.label{ 'data-group-id' => entry.group }= "group-#{entry.group}"
          - if entry.project != 0
            %span.project.label{ 'data-project-id' => entry.project }= "project-#{entry.project}"
          - if entry.issue != 0
            %span.issue{ 'data-issue-id' => entry.issue }= "\##{entry.issue}"
          %span.description= entry.description
        %td.date
          - if mode == :current_week
            %span.time= t('date.day_names')[entry.date.wday]
          - elsif mode != :no_date
            %span.time= "#{entry.date.strftime('%B %d, %Y')}"
          %span.duration= "#{entry.duration} h"

kairos/app/views/entries/import.html.haml
.container
  = render 'layouts/flash'
  %h3
    = t('message.user.import')
  %p
    = t('entries.import.description')
  %div.import-entries
    = form_tag import_entries_path, multipart: true do
      .form-group
        %label.sr-only{:for => 'file'}= t('entries.placeholder.select_file')
        = file_field_tag 'file', :accept => 'text/csv'
      = submit_tag 'Import', class: 'btn btn-default'

kairos/app/views/entries/index.html.haml
.container
  = render 'layouts/flash'
  %div.new-entry
    = form_for @entry, url: entries_path, class: 'form-horizontal' do |f|
      .main-container
        .time-container
          = f.date_field :date, :value => (@entry.date.strftime('%d/%m/%Y') unless @entry.date.nil?), :placeholder => 'dd/mm/yyyy', :tabindex => '1'
          = f.number_field :duration, :placeholder => '0 h', :tabindex => '2', step: 0.5
        .activity-container
          = f.select :activity, options_for_select(Activity.all.collect { |a| [a.name, a.id]}, :selected => (@entry.activity.id unless @entry.activity.nil?) ),
            { :include_blank => t('entries.placeholder.select_activity') },
            { :tabindex => '2', class: 'enhanced' }
        .group-container
          = f.select :group, {},
            { :include_blank => t('entries.placeholder.select_group') },
            { :tabindex => '3', class: 'enhanced', 'data-selected' => @entry.group }
        .description-container
          = f.text_field :description, :placeholder => t('entries.placeholder.enter_description'), :tabindex => '4'
        = submit_tag 'Log'
      .secondary-container
        .project-container
          = f.select :project, {},
            { :include_blank => t('entries.placeholder.select_project') },
            { :tabindex => '4', class: 'enhanced optional', 'data-selected' => @entry.project }
        .issue-container
          = f.select :issue, {},
            { :include_blank => t('entries.placeholder.select_issue') },
            { :tabindex => '5', class: 'enhanced optional', 'data-selected' => @entry.issue }
      = submit_tag 'Log', class: 'main'
  %div.last-entries
    = render 'entries/entries_listing', title: t('entries.categories.today'), mode: :no_date, entries: @entries_for_today
    = render 'entries/entries_listing', title: t('entries.categories.yesterday'), mode: :no_date, entries: @entries_for_yesterday
    = render 'entries/entries_listing', title: t('entries.categories.this_week'), mode: :current_week, entries: @entries_for_week
    = render 'entries/entries_listing', title: t('entries.categories.before_this_week'), mode: :current_date, entries: @entries